### ISSUE TITLE
Queue button should not show up when editing comments or answers

### ISSUE THREAD

**Issue by BobVul** [RootAccessOrg/TrickleEdit#2]

**Comment by Fleex255** [comment]
I think queueing would still be useful for edits to answers - people might want to sit down and revise a whole ton of answers without spewing tons of old questions back onto the front page. It would also have been helpful back when we did the image cleanup (before the official proclamation of the cleanup spree, at least).

Comment edits definitely shouldn't be queuable since they can't be edited at all after 5 minutes.

**Comment by BobVul** [comment]
@Fleex255 Yup, answers are planned, but if we end up using the API then that's a different endpoint. The questions are more important for a PoC, so I'll worry about the answers later.
